2023-01-23 21:22:37,223 INFO    MainThread:13174 [wandb_setup.py:_flush():69] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2023-01-23 21:22:37,223 WARNING MainThread:13174 [wandb_setup.py:_flush():69] could not save program above cwd: /Users/pedroberaldo/opt/anaconda3/envs/mlflow-a35db38b4ae81228d36bf1bbbc69f9f51ca6adad/bin/pytest
2023-01-23 21:22:37,223 INFO    MainThread:13174 [wandb_setup.py:_flush():69] setting login settings: {}
2023-01-23 21:22:37,223 INFO    MainThread:13174 [wandb_init.py:_log_setup():334] Logging user logs to /Users/pedroberaldo/coding/udacity/mlops/genre_classification/check_data/wandb/run-20230123_212237-2967jpee/logs/debug.log
2023-01-23 21:22:37,223 INFO    MainThread:13174 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/pedroberaldo/coding/udacity/mlops/genre_classification/check_data/wandb/run-20230123_212237-2967jpee/logs/debug-internal.log
2023-01-23 21:22:37,224 INFO    MainThread:13174 [wandb_init.py:init():367] calling init triggers
2023-01-23 21:22:37,224 INFO    MainThread:13174 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2023-01-23 21:22:37,224 INFO    MainThread:13174 [wandb_init.py:init():416] starting backend
2023-01-23 21:22:37,224 INFO    MainThread:13174 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-01-23 21:22:37,238 INFO    MainThread:13174 [backend.py:ensure_launched():123] starting backend process...
2023-01-23 21:22:37,246 INFO    MainThread:13174 [backend.py:ensure_launched():127] started backend process with pid: 13187
2023-01-23 21:22:37,249 INFO    MainThread:13174 [wandb_init.py:init():421] backend started and connected
2023-01-23 21:22:37,256 INFO    MainThread:13174 [wandb_init.py:init():461] updated telemetry
2023-01-23 21:22:37,265 INFO    MainThread:13174 [wandb_init.py:init():480] communicating current version
2023-01-23 21:22:37,931 INFO    MainThread:13174 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.13.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-01-23 21:22:37,932 INFO    MainThread:13174 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2023-01-23 21:22:38,285 INFO    MainThread:13174 [wandb_init.py:init():518] starting run threads in backend
2023-01-23 21:22:38,333 INFO    MainThread:13174 [wandb_run.py:_console_start():1476] atexit reg
2023-01-23 21:22:38,333 INFO    MainThread:13174 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.REDIRECT
2023-01-23 21:22:38,334 INFO    MainThread:13174 [wandb_run.py:_redirect():1344] Redirecting console.
2023-01-23 21:22:38,334 INFO    MainThread:13174 [redirect.py:install():213] install start
2023-01-23 21:22:38,334 INFO    MainThread:13174 [redirect.py:install():228] install stop
2023-01-23 21:22:38,335 INFO    MainThread:13174 [redirect.py:install():213] install start
2023-01-23 21:22:38,335 INFO    MainThread:13174 [redirect.py:install():228] install stop
2023-01-23 21:22:38,335 INFO    MainThread:13174 [wandb_run.py:_redirect():1390] Redirects installed.
2023-01-23 21:22:38,335 INFO    MainThread:13174 [wandb_init.py:init():542] run started, returning control to user process
2023-01-23 21:22:42,349 INFO    MainThread:13174 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2023-01-23 21:22:42,349 INFO    MainThread:13174 [wandb_run.py:_restore():1418] restore
2023-01-23 21:22:42,349 INFO    MainThread:13174 [redirect.py:uninstall():232] uninstall start
2023-01-23 21:22:42,349 INFO    MainThread:13174 [redirect.py:_stop():287] _stop: stdout
2023-01-23 21:22:42,349 INFO    MainThread:13174 [redirect.py:_stop():293] _stop closed: stdout
2023-01-23 21:22:42,387 INFO    stdout    :13174 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2023-01-23 21:22:42,387 INFO    stdout    :13174 [redirect.py:_pipe_relay():145] relay done done: stdout
2023-01-23 21:22:42,388 INFO    MainThread:13174 [redirect.py:_stop():299] _stop joined: stdout
2023-01-23 21:22:42,388 INFO    MainThread:13174 [redirect.py:_stop():301] _stop rd closed: stdout
2023-01-23 21:22:42,388 INFO    MainThread:13174 [redirect.py:uninstall():236] uninstall done
2023-01-23 21:22:42,388 INFO    MainThread:13174 [redirect.py:uninstall():232] uninstall start
2023-01-23 21:22:42,388 INFO    MainThread:13174 [redirect.py:_stop():287] _stop: stderr
2023-01-23 21:22:42,388 INFO    MainThread:13174 [redirect.py:_stop():293] _stop closed: stderr
2023-01-23 21:22:42,389 INFO    stderr    :13174 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2023-01-23 21:22:42,389 INFO    stderr    :13174 [redirect.py:_pipe_relay():145] relay done done: stderr
2023-01-23 21:22:42,390 INFO    MainThread:13174 [redirect.py:_stop():299] _stop joined: stderr
2023-01-23 21:22:42,390 INFO    MainThread:13174 [redirect.py:_stop():301] _stop rd closed: stderr
2023-01-23 21:22:42,390 INFO    MainThread:13174 [redirect.py:uninstall():236] uninstall done
2023-01-23 21:22:42,641 INFO    MainThread:13174 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1005
  total_bytes: 1005
}

2023-01-23 21:22:44,648 INFO    MainThread:13174 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 55710
  total_bytes: 55710
}

2023-01-23 21:22:45,770 INFO    MainThread:13174 [wandb_run.py:_show_files():1790] logging synced files
